export const TIME_MIN = 0;
export const TIME_MAX = 100;
export const MOCK_START_DATE = new Date('2024-01-01T00:00:00Z');
export const MOCK_END_DATE = new Date('2024-12-31T23:59:59Z');
export const MOCK_START_MS = MOCK_START_DATE.getTime();
export const MOCK_END_MS = MOCK_END_DATE.getTime();
export const MOCK_START_SEC = MOCK_START_MS / 1000;
export const MOCK_END_SEC = MOCK_END_MS / 1000;
export const TIME_STEP_DEFAULT = 1;
export const PLAYBACK_SPEED_DEFAULT = 10; // units per second
export const TIME_WINDOW_DEFAULT = 5;
